vich_uploader:
    db_driver: orm

    mappings:
        biens_img:
           uri_prefix: /images/biens
           upload_destination: '%kernel.project_dir%/public/images/biens'
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
